spring:
  application:
    name: api-gateway
 



server:
  port: 9001

Zuul:
 routes:
  movieCatalogue-services:
    path: /movieCatalogue-services/**
    service-id: catalogue-service
  movie-services:
    path: /movie-services/**
    service-id: movie-service
    
  movieRating-services:
    path: /movieRating-services/**
    service-id: movieRating-service
    
    
 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   
    